### ISSUE TITLE
Java outended

### ISSUE THREAD

**Issue by vlotho** [YunoHost-Apps/minecraft_ynh#11]
Hi,
Java is now outdated in the installation script.
If I directly modify the installation script and re-upload it, I get a message: corrupt source
https://paste.yunohost.org/raw/evowaqotaq

**Comment by ericgaspar** [comment]
Should be fixed in testing branch
`https://github.com/YunoHost-Apps/minecraft_ynh/tree/testing`

**Comment by vlotho** [comment]
a problem with the manifest.json.
it doesn't detect it.
and in command line it just shows me:
error: cancellation

**Comment by ericgaspar** [comment]
I cannot reproduce your issue. Are you installing from master? `sudo yunohost app install https://github.com/YunoHost-Apps/minecraft_ynh`

**Comment by vlotho** [comment]
no it's good, it works. thank you :)
