### ISSUE TITLE
install "mcrcon" optional?

### ISSUE THREAD

**Issue by jedie** [YunoHost-Apps/minecraft_ynh#18]
Would be great to install https://github.com/Tiiffi/mcrcon too, isn't it? Maybe optional?

**Comment by dhuschde** [comment]
That is to connect from your Computer to the Server.
Installing the client wouldn't make sense on the Server.

**Comment by ericgaspar** [comment]
[mcrcon](https://github.com/Tiiffi/mcrcon) is now installed as default (in the testing branch)
