### ISSUE TITLE
Minecraft Console

### ISSUE THREAD

**Issue by dhuschde** [YunoHost-Apps/minecraft_ynh#25]
Hey, I have the following Problem:
I can't find the Minecraft Console nor does RCON work.

How can I use the Minecraft Console?
![grafik](https://user-images.githubusercontent.com/85834680/132321818-c7ba79be-478a-4534-a490-205cb80cb962.png)

**Comment by ericgaspar** [comment]
The wrong port was open by the install script... `25565` instead of the rcon default `25575`
#26 should fix that

**Comment by ericgaspar** [comment]
You need the
-H server adress
-P Port (we are using 25575 as default)
-p password

**Comment by ericgaspar** [comment]
The rcon port `25575` wasn't opened. #27 should correct that.
