### ISSUE TITLE
Can't install on : Raspberry Pi 4 - RPI OS-lite legacy (Debian 10) with Yunohost script install

### ISSUE THREAD

**Issue by HappyClem** [YunoHost-Apps/minecraft_ynh#32]
Hello,

I was trying to install this app on my config and go this errors : 

https://paste.yunohost.org/raw/wulovabobi

Looks like some dependencies are not available.

Harware : Raspberry pi 4 8Go
Flash image : Rapsberry OS-lite Legacy (Debian 10, because Yunohost image is x32 and RPI OS latest version is Debian 11 which Yunohost does not support from the installation script)
I have access to my yunohost webinterface.
I did change and delete the default pi user and create a new one with sudo priviliges.

**Comment by ericgaspar** [comment]
Minecraft server can't be installed in ARM architecture (for now java17 is only installable on amd64 arch).
