### ISSUE TITLE
How to install 1.18.2 minecraft server

### ISSUE THREAD

**Issue by Frikigi** [YunoHost-Apps/minecraft_ynh#36]
EN 
> Hi,
> I've installed the script and it's work very well. I'm on Spigot server. I want to insall a minecraft server compatible with the version 1.18.2 and i don't know how to do this. 
> Somebody have an Idea ? 
> 
> Thank you 

FR

> 
> Bonjour,
> J'ai installé le script et il fonctionne a la perfection. Je souhaiterais installer une version de minecraft server (actuellement je suis sur Spigot) compatible avec la 1.18.2. Je ne sais pas comment faire ça. Quelqu'un a une idée pour réaliser cela ?
> D'avance merci.

**Comment by ericgaspar** [comment]
#37 incoming upgrade
