### ISSUE TITLE
Option for custom jar

### ISSUE THREAD

**Issue by ChildishGiant** [YunoHost-Apps/minecraft_ynh#7]
#3 and #5 are both about outdated versions. I think it'd make more sense for there to be a field for a custom jar. That way the app doesn't need updating every time there's a new version of minecraft. It seems like it shouldn't be too hard to implement seeing as there's a SOURCE_URL var in each config.

**Comment by ericgaspar** [comment]
Testing  now have the last versions... https://github.com/YunoHost-Apps/minecraft_ynh/tree/testing
